/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SearchIndexImport } from './routes/search/index'
import { Route as SearchQueryImport } from './routes/search/$query'
import { Route as AlbumAlbumidImport } from './routes/album/$albumid'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SearchIndexRoute = SearchIndexImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRoute,
} as any)

const SearchQueryRoute = SearchQueryImport.update({
  id: '/search/$query',
  path: '/search/$query',
  getParentRoute: () => rootRoute,
} as any)

const AlbumAlbumidRoute = AlbumAlbumidImport.update({
  id: '/album/$albumid',
  path: '/album/$albumid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/album/$albumid': {
      id: '/album/$albumid'
      path: '/album/$albumid'
      fullPath: '/album/$albumid'
      preLoaderRoute: typeof AlbumAlbumidImport
      parentRoute: typeof rootRoute
    }
    '/search/$query': {
      id: '/search/$query'
      path: '/search/$query'
      fullPath: '/search/$query'
      preLoaderRoute: typeof SearchQueryImport
      parentRoute: typeof rootRoute
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album/$albumid': typeof AlbumAlbumidRoute
  '/search/$query': typeof SearchQueryRoute
  '/search': typeof SearchIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album/$albumid': typeof AlbumAlbumidRoute
  '/search/$query': typeof SearchQueryRoute
  '/search': typeof SearchIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/album/$albumid': typeof AlbumAlbumidRoute
  '/search/$query': typeof SearchQueryRoute
  '/search/': typeof SearchIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/album/$albumid' | '/search/$query' | '/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/album/$albumid' | '/search/$query' | '/search'
  id: '__root__' | '/' | '/album/$albumid' | '/search/$query' | '/search/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumAlbumidRoute: typeof AlbumAlbumidRoute
  SearchQueryRoute: typeof SearchQueryRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumAlbumidRoute: AlbumAlbumidRoute,
  SearchQueryRoute: SearchQueryRoute,
  SearchIndexRoute: SearchIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/album/$albumid",
        "/search/$query",
        "/search/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/album/$albumid": {
      "filePath": "album/$albumid.tsx"
    },
    "/search/$query": {
      "filePath": "search/$query.tsx"
    },
    "/search/": {
      "filePath": "search/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
